module.exports = {
    processors: ["stylelint-processor-html"],
    extends: ["stylelint-config-standard"],
    plugins: ["stylelint-order"], // stylelint-order是CSS属性排序插件
    rules: {
      "no-descending-specificity": null, // 顺序校验
      "color-hex-case": "lower", // 颜色值为小写字母(stylelint-config-standard)
      "color-no-invalid-hex": true, // 颜色值不能为无效值(stylelint-config-standard)
      "font-family-name-quotes": "always-where-recommended", // 字体系列中命名时带引号
      "function-url-quotes": "always", // url地址一定要写引号(wrong: background-image:url(adf/sfsa.jpg))
      "number-leading-zero": "never", // 要求或分数低于1的数字禁止前导零(wrong: line-height: 0.5px -> right: line-height:.5px)
      "number-no-trailing-zeros": true, // 禁止在数量尾随零(wrong: top: 1.0px -> right: top: 1px)
      "string-quotes": "double", // 指定字串，双引号
      "length-zero-no-unit": true, // 禁止单位零长度 exp: a { top: 0px } -> a { top: 0 }
      "value-keyword-case": "lower", // 指定小写关键字的值 exp:a { display: BLOCK; } -> a { display: block; }
      "value-list-comma-newline-after": "always-multi-line", // 在值列表的逗号后指定一个换行符或禁止留有空格
      "shorthand-property-no-redundant-values": true, // 不允许在简写属性冗余值
      "property-case": "lower", // 为属性指定小写(stylelint-config-standard)
      "keyframe-declaration-no-important": true, // 不允许!important在关键帧声明
      "block-closing-brace-empty-line-before": "never", // 不允许关闭括号前空一行(stylelint-config-standard)
      "block-closing-brace-newline-after": "always", // 需要一个换行符关闭括号后的空白(stylelint-config-standard)
      "block-opening-brace-newline-after": "always-multi-line", // 开括号的块之后需要新的一行(stylelint-config-standard)
      "selector-class-pattern": "^[a-z]+([a-z0-9]?|[a-z0-9\\-\\_]*[a-z0-9])$", // 指定一个模式类选择符，限制选择器名称写法
      "selector-id-pattern": "^[a-z]+([a-z0-9]?|[a-z0-9\\-\\_]*[a-z0-9])$", // 指定一个模式，id选择器，限制选择器名称写法
      "value-keyword-case": "lower", // 属性值小写
      "no-empty-source": null, // 不允许空的来源
      "at-rule-no-unknown": null, // 不允许at-rules不明
      "indentation": 4, // 指定缩进(stylelint-config-standard)
      "max-nesting-depth": 3, // 允许嵌套的深度为3
      "no-duplicate-selectors": true, // 不允许重复的选择器
      "no-eol-whitespace": true, // 不允许行尾空白(stylelint-config-standard)
      "rule-empty-line-before": "never-multi-line", // 规则之间不允许空行
      "declaration-empty-line-before": "never", // 不允许空行
      "order/order": [ // 指定声明块内的内容顺序
        ["custom-properties", "declarations"], 
        // {
        //   "disableFix": true
        // }  
      ],
      // css编写顺序规定
      "order/properties-order": [
        "position",
        "z-index",      
        "top",
        "bottom",
        "left",         
        "right",
        "float",
        "clear",
        "columns",
        "columns-width",
        "columns-count",
        "column-rule",
        "column-rule-width",
        "column-rule-style",
        "column-rule-color",
        "column-fill",
        "column-span",
        "column-gap",      
        "display",
        "grid",
        "grid-template-rows",
        "grid-template-columns",
        "grid-template-areas",
        "grid-auto-rows",
        "grid-auto-columns",
        "grid-auto-flow",
        "grid-column-gap",
        "grid-row-gap",
        "grid-template",
        "grid-template-rows",
        "grid-template-columns",
        "grid-template-areas",
        "grid-gap",
        "grid-row-gap",
        "grid-column-gap",
        "grid-area",
        "grid-row-start",
        "grid-row-end",
        "grid-column-start",
        "grid-column-end",
        "grid-column",
        "grid-column-start",
        "grid-column-end",
        "grid-row",
        "grid-row-start",
        "grid-row-end",      
        "flex",
        "flex-grow",
        "flex-shrink",
        "flex-basis",
        "flex-flow",
        "flex-direction",
        "flex-wrap",
        "justify-content",
        "align-content",
        "align-items",
        "align-self",
        "order",
        "table-layout",
        "empty-cells",
        "caption-side",
        "border-collapse",
        "border-spacing",
        "list-style",
        "list-style-type",
        "list-style-position",
        "list-style-image",
        "ruby-align",
        "ruby-merge",
        "ruby-position",
        "box-sizing",
        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",  
        "border",
        "border-width",
        "border-top-width",
        "border-right-width",
        "border-bottom-width",
        "border-left-width",
        "border-style",
        "border-top-style",
        "border-right-style",
        "border-bottom-style",
        "border-left-style",
        "border-color",
        "border-top-color",
        "border-right-color",
        "border-bottom-color",
        "border-left-color",
        "border-image",
        "border-image-source",
        "border-image-slice",
        "border-image-width",
        "border-image-outset",
        "border-image-repeat",
        "border-top",
        "border-top-width",
        "border-top-style",
        "border-top-color",
        "border-top",
        "border-right-width",
        "border-right-style",
        "border-right-color",
        "border-bottom",
        "border-bottom-width",
        "border-bottom-style",
        "border-bottom-color",
        "border-left",
        "border-left-width",
        "border-left-style",
        "border-left-color",
        "border-radius",
        "border-top-right-radius",
        "border-bottom-right-radius",
        "border-bottom-left-radius",
        "border-top-left-radius",
        "outline",
        "outline-width",
        "outline-color",
        "outline-style",
        "outline-offset",
        "overflow",
        "overflow-x",
        "overflow-y",
        "resize",
        "visibility",
        "font",
        "font-style",
        "font-variant",
        "font-weight",
        "font-stretch",
        "font-size",
        "font-family",
        "font-synthesis",
        "font-size-adjust",
        "font-kerning",        
        "line-height",
        "text-align",
        "text-align-last",
        "vertical-align",      
        "text-overflow",
        "text-justify",
        "text-transform",
        "text-indent",
        "text-emphasis",
        "text-emphasis-style",
        "text-emphasis-color",
        "text-emphasis-position",
        "text-decoration",
        "text-decoration-color",
        "text-decoration-style",
        "text-decoration-line",
        "text-underline-position",
        "text-shadow",      
        "white-space",
        "overflow-wrap",
        "word-wrap",
        "word-break",
        "line-break",
        "hyphens",
        "letter-spacing",
        "word-spacing",
        "quotes",
        "tab-size",
        "orphans",
        "writing-mode",
        "text-combine-upright",
        "unicode-bidi",
        "text-orientation",
        "direction",
        "text-rendering",
        "font-feature-settings",
        "font-language-override",
        "image-rendering",
        "image-orientation",
        "image-resolution",
        "shape-image-threshold",
        "shape-outside",
        "shape-margin",
        "color",
        "background",
        "background-image",
        "background-position",
        "background-size",
        "background-repeat",
        "background-origin",
        "background-clip",
        "background-attachment",
        "background-color",
        "background-blend-mode",
        "isolation",
        "clip-path",
        "mask",
        "mask-image",
        "mask-mode",
        "mask-position",
        "mask-size",
        "mask-repeat",
        "mask-origin",
        "mask-clip",
        "mask-composite",
        "mask-type",
        "filter",
        "box-shadow",
        "opacity",
        "transform-style",
        "transform",
        "transform-box",
        "transform-origin",
        "perspective",
        "perspective-origin",
        "backface-visibility",
        "transition",
        "transition-property",
        "transition-duration",
        "transition-timing-function",
        "transition-delay",
        "animation",
        "animation-name",
        "animation-duration",
        "animation-timing-function",
        "animation-delay",
        "animation-iteration-count",
        "animation-direction",
        "animation-fill-mode",
        "animation-play-state",
        "scroll-behavior",
        "scroll-snap-type",
        "scroll-snap-destination",
        "scroll-snap-coordinate",
        "cursor",
        "touch-action",
        "caret-color",
        "ime-mode",
        "object-fit",
        "object-position",
        "content",
        "counter-reset",
        "counter-increment",
        "will-change",
        "pointer-events",
        "all",
        "page-break-before",
        "page-break-after",
        "page-break-inside",
        "widows"
      ],
    }
}